# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'github-api-test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for github-api-test
  pod 'Alamofire'
  pod 'PKHUD'
  pod 'ESPullToRefresh'
  pod 'Repeat'
  pod 'Realm'
  pod 'RealmSwift'

  target 'github-api-testTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'github-api-testUITests' do
    # Pods for testing
  end

end
